# Generated by Django 5.0.6 on 2024-07-18 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='I did not write a bio yet', max_length=500)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics')),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('other_url', models.URLField(blank=True, null=True)),
                ('link_image', models.ImageField(default='links/personal_profile.png', upload_to='links')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
